version: "3.7"
services:
  webapp:
    image: desafio-ruby-backend
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - "/app/scripts/nginx"
      - ".:/app"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    env_file:
      - .postgres_env
